# ci.yml file for GitHub Actions
name: CI

on:
  push:
    branches:
      - master

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run buildprep

      - name: Build storybook
        run: npm run build-storybook

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: storybook-static
